In [1]:
import pandas as pd

In [15]:
df_proc = pd.read_csv('../processed_data/attendance_w_team_perf.csv')

In [10]:
df_standings = pd.read_csv('../processed_data/standings.csv')

In [14]:
df_standings.loc[((df_standings['year'] == 2006) | (df_standings['year'] == 2007) | (df_standings['year'] == 2008) ) & (df_standings['sb_winner'] != 'No Superbowl') ]

,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking,playoffs,sb_winner,team_full_name
198,2006,12,4,427,360,67,4.2,1.7,5.9,6.9,-1.1,Playoffs,Won Superbowl,Indianapolis Colts
239,2007,10,6,373,351,22,1.4,1.9,3.3,2.8,0.4,Playoffs,Won Superbowl,New York Giants
258,2008,12,4,347,223,124,7.8,2.0,9.8,1.6,8.2,Playoffs,Won Superbowl,Pittsburgh Steelers

In [16]:
df_proc

,year,team_full_name,week,weekly_attendance,home,Sb_winners,Sb_winners_prev_years,Playoff_prev_years,Bad_streak,Medium_streak,Good_streak
0,2000,Arizona Cardinals,1,77434.0,False,NaN,NaN,NaN,True,False,False
1,2000,Arizona Cardinals,2,66009.0,True,NaN,NaN,NaN,True,False,False
2,2000,Arizona Cardinals,3,NaN,NaN,NaN,NaN,NaN,True,False,False
3,2000,Arizona Cardinals,4,71801.0,True,NaN,NaN,NaN,True,False,False
4,2000,Arizona Cardinals,5,66985.0,False,NaN,NaN,NaN,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
10841,2019,Washington Redskins,13,71504.0,False,NaN,NaN,NaN,True,False,False
10842,2019,Washington Redskins,14,77296.0,False,NaN,NaN,NaN,True,False,False
10843,2019,Washington Redskins,15,63246.0,True,NaN,NaN,NaN,False,True,False
10844,2019,Washington Redskins,16,66083.0,True,NaN,NaN,NaN,False,True,False
10845,2019,Washington Redskins,17,90646.0,False,NaN,NaN,NaN,False,True,False

In [4]:
df_orig_att = pd.read_csv('../original_data/attendance.csv')

In [7]:
df_orig_att

,team,team_name,year,total,home,away,week,weekly_attendance
0,Arizona,Cardinals,2000,893926,387475,506451,1,77434.0
1,Arizona,Cardinals,2000,893926,387475,506451,2,66009.0
2,Arizona,Cardinals,2000,893926,387475,506451,3,NaN
3,Arizona,Cardinals,2000,893926,387475,506451,4,71801.0
4,Arizona,Cardinals,2000,893926,387475,506451,5,66985.0
...,...,...,...,...,...,...,...,...
10841,Washington,Redskins,2019,1101466,523906,577560,13,71504.0
10842,Washington,Redskins,2019,1101466,523906,577560,14,77296.0
10843,Washington,Redskins,2019,1101466,523906,577560,15,63246.0
10844,Washington,Redskins,2019,1101466,523906,577560,16,66083.0
10845,Washington,Redskins,2019,1101466,523906,577560,17,90646.0

In [9]:
df_orig_att.loc[df_orig_att['year'] == 2007]

,team,team_name,year,total,home,away,week,weekly_attendance
3774,Arizona,Cardinals,2007,1072427,516646,555781,1,68111.0
3775,Arizona,Cardinals,2007,1072427,516646,555781,2,64542.0
3776,Arizona,Cardinals,2007,1072427,516646,555781,3,71372.0
3777,Arizona,Cardinals,2007,1072427,516646,555781,4,64844.0
3778,Arizona,Cardinals,2007,1072427,516646,555781,5,61788.0
...,...,...,...,...,...,...,...,...
4313,Washington,Redskins,2007,1259463,704722,554741,13,85831.0
4314,Washington,Redskins,2007,1259463,704722,554741,14,82213.0
4315,Washington,Redskins,2007,1259463,704722,554741,15,77899.0
4316,Washington,Redskins,2007,1259463,704722,554741,16,63634.0
4317,Washington,Redskins,2007,1259463,704722,554741,17,90910.0

In [8]:
df_orig_att[['team', 'team_name']].value_counts()

team           team_name
Arizona        Cardinals     340
Atlanta        Falcons       340
Tennessee      Titans        340
Tampa Bay      Buccaneers    340
Seattle        Seahawks      340
San Francisco  49ers         340
Pittsburgh     Steelers      340
Philadelphia   Eagles        340
Oakland        Raiders       340
New York       Jets          340
               Giants        340
New Orleans    Saints        340
New England    Patriots      340
Minnesota      Vikings       340
Miami          Dolphins      340
Washington     Redskins      340
Cleveland      Browns        340
Baltimore      Ravens        340
Jacksonville   Jaguars       340
Indianapolis   Colts         340
Green Bay      Packers       340
Detroit        Lions         340
Denver         Broncos       340
Dallas         Cowboys       340
Kansas City    Chiefs        340
Cincinnati     Bengals       340
Chicago        Bears         340
Carolina       Panthers      340
Buffalo        Bills         340
Houston        Texans        306
San Diego      Chargers      289
St. Louis      Rams          272
Los Angeles    Rams           68
               Chargers       51
Name: count, dtype: int64

## Weather data

In [25]:
df_att_modified = pd.read_csv('../processed_data/attendance_w_team_perf.csv')

In [47]:
df_0609 = pd.read_csv('../../export_2006-2009.csv')
df_1014 = pd.read_csv('../../export_2010-2014.csv')
df_1520 = pd.read_csv('../../export_2015-2020.csv')
df_weather = pd.concat([df_0609, df_1014, df_1520], ignore_index=True)

In [24]:
type(df_0609['date'][0])

str

In [22]:
df_0609['wpgt'].value_counts()

Series([], Name: count, dtype: int64)

In [50]:
df_weather['date'] = pd.to_datetime(df_weather['date'])

In [98]:
df_pats = df_att_modified.loc[(df_att_modified['year']>= 2006) & (df_att_modified['team_name'] == 'patriots') & (df_att_modified['location'] == 'home')]

In [56]:
df_games = pd.read_csv('../original_data/games.csv')
df_att_original = pd.read_csv('../original_data/attendance.csv')

In [66]:
df_games.loc[(df_games['year'] == df_att_modified['year']) ]

ValueError: Can only compare identically-labeled Series objects

In [75]:
df_att_modified

,team,team_name,opponent_team,opponent_team_name,location,year,total,home,away,week,...,stadium,home_team,capacity,capacity_rate,Sb_winners,Sb_winners_prev_years,Playoff_prev_years,Bad_streak,Medium_streak,Good_streak
0,Arizona,cardinals,New York,giants,away,2000,893926,387475,506451,1,...,State Farm Stadium,Arizona Cardinals,63400,0.818762,False,False,False,True,False,False
1,Arizona,cardinals,Dallas,cowboys,home,2000,893926,387475,506451,2,...,State Farm Stadium,Arizona Cardinals,63400,0.960475,False,False,False,True,False,False
2,Arizona,cardinals,NaN,NaN,NaN,2000,893926,387475,506451,3,...,State Farm Stadium,Arizona Cardinals,63400,NaN,False,False,False,True,False,False
3,Arizona,cardinals,Green Bay,packers,home,2000,893926,387475,506451,4,...,State Farm Stadium,Arizona Cardinals,63400,0.882996,False,False,False,True,False,False
4,Arizona,cardinals,San Francisco,49ers,away,2000,893926,387475,506451,5,...,State Farm Stadium,Arizona Cardinals,63400,0.946481,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10841,Washington,redskins,Carolina,panthers,away,2019,1101466,523906,577560,13,...,Commanders Field,Washington Redskins,62000,0.867084,False,False,False,True,False,False
10842,Washington,redskins,Green Bay,packers,away,2019,1101466,523906,577560,14,...,Commanders Field,Washington Redskins,62000,0.802111,False,False,False,True,False,False
10843,Washington,redskins,Philadelphia,eagles,home,2019,1101466,523906,577560,15,...,Commanders Field,Washington Redskins,62000,0.980299,False,False,False,False,True,False
10844,Washington,redskins,New York,giants,home,2019,1101466,523906,577560,16,...,Commanders Field,Washington Redskins,62000,0.938214,False,False,False,False,True,False
10845,Washington,redskins,Dallas,cowboys,away,2019,1101466,523906,577560,17,...,Commanders Field,Washington Redskins,62000,0.683979,False,False,False,False,True,False

In [74]:
df_att_modified.loc[:,'date'] = df_att_modified.apply(lambda x: df_games.loc[(df_games['year'] == x['year']) & (df_games['week'] == x['week']) & (df_games['home_team'] == 'New England patriots'), 'date'], axis=1)

ValueError: Cannot set a DataFrame without columns to the column date

In [81]:
df_pats

,home,away,week,weekly_attendance,stadium,home_team,capacity,capacity_rate,Sb_winners,Sb_winners_prev_years,Playoff_prev_years,Bad_streak,Medium_streak,Good_streak,date
3536,550048,560722,1,68756.0,Gillette Stadium,New England Patriots,66829,0.971973,False,True,True,True,False,False,NaN
3538,550048,560722,3,68756.0,Gillette Stadium,New England Patriots,66829,0.971973,False,True,True,True,False,False,NaN
3540,550048,560722,5,68756.0,Gillette Stadium,New England Patriots,66829,0.971973,False,True,True,False,True,False,NaN
3544,550048,560722,9,68756.0,Gillette Stadium,New England Patriots,66829,0.971973,False,True,True,False,False,True,NaN
3545,550048,560722,10,68756.0,Gillette Stadium,New England Patriots,66829,0.971973,False,True,True,False,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10649,527024,560880,8,65878.0,Gillette Stadium,New England Patriots,66829,1.000000,True,True,True,False,False,True,NaN
10653,527024,560880,12,65878.0,Gillette Stadium,New England Patriots,66829,1.000000,True,True,True,False,False,True,NaN
10655,527024,560880,14,65878.0,Gillette Stadium,New England Patriots,66829,1.000000,True,True,True,False,False,True,NaN
10657,527024,560880,16,65878.0,Gillette Stadium,New England Patriots,66829,1.000000,True,True,True,False,True,False,NaN
10658,527024,560880,17,65878.0,Gillette Stadium,New England Patriots,66829,1.000000,True,True,True,False,True,False,NaN

In [99]:
df_games_ne = df_games[(df_games['home_team'] == 'New England Patriots') & (df_games['year']>2006)][['year', 'week', 'date']]
df_games_ne = df_games_ne.loc[~df_games_ne['week'].isin(['WildCard','Division', 'ConfChamp', 'SuperBowl'])]
df_pats = df_att_modified.loc[(df_att_modified['year']>= 2006) & (df_att_modified['team_name'] == 'patriots') & (df_att_modified['location'] == 'home')]
df_games_ne['week'] = df_games_ne['week'].astype(int)
# Merge on year and week
df_pats = df_pats.merge(df_games_ne, on=['year', 'week'], how='left')

In [87]:
print(df_pats[['year', 'week']].dtypes)
print(df_games_ne[['year', 'week']].dtypes)

year    int64
week    int64
dtype: object
year    int64
week    int64
dtype: object

In [94]:
df_games['home_team']

0         Minnesota Vikings
1        Kansas City Chiefs
2       Washington Redskins
3           Atlanta Falcons
4       Pittsburgh Steelers
               ...
5319     Kansas City Chiefs
5320      Green Bay Packers
5321     Kansas City Chiefs
5322    San Francisco 49ers
5323     Kansas City Chiefs
Name: home_team, Length: 5324, dtype: object

In [95]:
df_games_ne = df_games[(df_games['home_team'] == 'New England Patriots') & (df_games['year']>2006)]
df_games_ne

,year,week,home_team,away_team,winner,tie,day,date,time,pts_win,pts_loss,yds_win,turnovers_win,yds_loss,turnovers_loss,home_team_name,home_team_city,away_team_name,away_team_city
1883,2007,2,New England Patriots,San Diego Chargers,New England Patriots,NaN,Sun,September 16,8:24PM,38,14,407,2,201,3,Patriots,New England,Chargers,San Diego
1888,2007,3,New England Patriots,Buffalo Bills,New England Patriots,NaN,Sun,September 23,1:02PM,38,7,485,1,193,2,Patriots,New England,Bills,Buffalo
1920,2007,5,New England Patriots,Cleveland Browns,New England Patriots,NaN,Sun,October 7,1:02PM,34,17,412,0,353,4,Patriots,New England,Browns,Cleveland
1967,2007,8,New England Patriots,Washington Redskins,New England Patriots,NaN,Sun,October 28,4:17PM,52,7,486,1,224,4,Patriots,New England,Redskins,Washington
2027,2007,12,New England Patriots,Philadelphia Eagles,New England Patriots,NaN,Sun,November 25,8:23PM,31,28,410,0,391,3,Patriots,New England,Eagles,Philadelphia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,2019,12,New England Patriots,Dallas Cowboys,New England Patriots,NaN,Sun,November 24,4:25PM,13,9,282,0,321,1,Patriots,New England,Cowboys,Dallas
5262,2019,14,New England Patriots,Kansas City Chiefs,Kansas City Chiefs,NaN,Sun,December 8,4:25PM,23,16,346,2,278,1,Patriots,New England,Chiefs,Kansas City
5282,2019,16,New England Patriots,Buffalo Bills,New England Patriots,NaN,Sat,December 21,4:30PM,24,17,414,1,268,0,Patriots,New England,Bills,Buffalo
5301,2019,17,New England Patriots,Miami Dolphins,Miami Dolphins,NaN,Sun,December 29,1:00PM,27,24,389,0,352,2,Patriots,New England,Dolphins,Miami
5314,2019,WildCard,New England Patriots,Tennessee Titans,Tennessee Titans,NaN,Sat,January 4,8:15PM,20,13,272,1,307,2,Patriots,New England,Titans,Tennessee

In [100]:
df_pats

,team,team_name,opponent_team,opponent_team_name,location,year,total,home,away,week,...,capacity_rate,Sb_winners,Sb_winners_prev_years,Playoff_prev_years,Bad_streak,Medium_streak,Good_streak,date_x,date_y,date
0,New England,patriots,Buffalo,bills,home,2006,1110770,550048,560722,1,...,0.971973,False,True,True,True,False,False,NaN,NaN,NaN
1,New England,patriots,Denver,broncos,home,2006,1110770,550048,560722,3,...,0.971973,False,True,True,True,False,False,NaN,NaN,NaN
2,New England,patriots,Miami,dolphins,home,2006,1110770,550048,560722,5,...,0.971973,False,True,True,False,True,False,NaN,NaN,NaN
3,New England,patriots,Indianapolis,colts,home,2006,1110770,550048,560722,9,...,0.971973,False,True,True,False,False,True,NaN,NaN,NaN
4,New England,patriots,New York,jets,home,2006,1110770,550048,560722,10,...,0.971973,False,True,True,False,False,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,New England,patriots,Cleveland,browns,home,2019,1087904,527024,560880,8,...,1.000000,True,True,True,False,False,True,NaN,NaN,October 27
108,New England,patriots,Dallas,cowboys,home,2019,1087904,527024,560880,12,...,1.000000,True,True,True,False,False,True,NaN,NaN,November 24
109,New England,patriots,Kansas City,chiefs,home,2019,1087904,527024,560880,14,...,1.000000,True,True,True,False,False,True,NaN,NaN,December 8
110,New England,patriots,Buffalo,bills,home,2019,1087904,527024,560880,16,...,1.000000,True,True,True,False,True,False,NaN,NaN,December 21
111,New England,patriots,Miami,dolphins,home,2019,1087904,527024,560880,17,...,1.000000,True,True,True,False,True,False,NaN,NaN,December 29

In [70]:
df_games

,year,week,home_team,away_team,winner,tie,day,date,time,pts_win,pts_loss,yds_win,turnovers_win,yds_loss,turnovers_loss,home_team_name,home_team_city,away_team_name,away_team_city
0,2000,1,Minnesota Vikings,Chicago Bears,Minnesota Vikings,NaN,Sun,September 3,1:00PM,30,27,374,1,425,1,Vikings,Minnesota,Bears,Chicago
1,2000,1,Kansas City Chiefs,Indianapolis Colts,Indianapolis Colts,NaN,Sun,September 3,1:00PM,27,14,386,2,280,1,Chiefs,Kansas City,Colts,Indianapolis
2,2000,1,Washington Redskins,Carolina Panthers,Washington Redskins,NaN,Sun,September 3,1:01PM,20,17,396,0,236,1,Redskins,Washington,Panthers,Carolina
3,2000,1,Atlanta Falcons,San Francisco 49ers,Atlanta Falcons,NaN,Sun,September 3,1:02PM,36,28,359,1,339,1,Falcons,Atlanta,49ers,San Francisco
4,2000,1,Pittsburgh Steelers,Baltimore Ravens,Baltimore Ravens,NaN,Sun,September 3,1:02PM,16,0,336,0,223,1,Steelers,Pittsburgh,Ravens,Baltimore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5319,2019,Division,Kansas City Chiefs,Houston Texans,Kansas City Chiefs,NaN,Sun,January 12,3:05PM,51,31,434,1,442,1,Chiefs,Kansas City,Texans,Houston
5320,2019,Division,Green Bay Packers,Seattle Seahawks,Green Bay Packers,NaN,Sun,January 12,6:40PM,28,23,344,0,375,0,Packers,Green Bay,Seahawks,Seattle
5321,2019,ConfChamp,Kansas City Chiefs,Tennessee Titans,Kansas City Chiefs,NaN,Sun,January 19,3:05PM,35,24,404,0,295,0,Chiefs,Kansas City,Titans,Tennessee
5322,2019,ConfChamp,San Francisco 49ers,Green Bay Packers,San Francisco 49ers,NaN,Sun,January 19,6:40PM,37,20,354,0,358,3,49ers,San Francisco,Packers,Green Bay
5323,2019,SuperBowl,Kansas City Chiefs,San Francisco 49ers,Kansas City Chiefs,NaN,Sun,February 2,6:30PM,31,20,397,2,351,2,Chiefs,Kansas City,49ers,San Francisco

In [63]:
df_att_modified

,team,team_name,opponent_team,opponent_team_name,location,year,total,home,away,week,...,stadium,home_team,capacity,capacity_rate,Sb_winners,Sb_winners_prev_years,Playoff_prev_years,Bad_streak,Medium_streak,Good_streak
0,Arizona,cardinals,New York,giants,away,2000,893926,387475,506451,1,...,State Farm Stadium,Arizona Cardinals,63400,0.818762,False,False,False,True,False,False
1,Arizona,cardinals,Dallas,cowboys,home,2000,893926,387475,506451,2,...,State Farm Stadium,Arizona Cardinals,63400,0.960475,False,False,False,True,False,False
2,Arizona,cardinals,NaN,NaN,NaN,2000,893926,387475,506451,3,...,State Farm Stadium,Arizona Cardinals,63400,NaN,False,False,False,True,False,False
3,Arizona,cardinals,Green Bay,packers,home,2000,893926,387475,506451,4,...,State Farm Stadium,Arizona Cardinals,63400,0.882996,False,False,False,True,False,False
4,Arizona,cardinals,San Francisco,49ers,away,2000,893926,387475,506451,5,...,State Farm Stadium,Arizona Cardinals,63400,0.946481,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10841,Washington,redskins,Carolina,panthers,away,2019,1101466,523906,577560,13,...,Commanders Field,Washington Redskins,62000,0.867084,False,False,False,True,False,False
10842,Washington,redskins,Green Bay,packers,away,2019,1101466,523906,577560,14,...,Commanders Field,Washington Redskins,62000,0.802111,False,False,False,True,False,False
10843,Washington,redskins,Philadelphia,eagles,home,2019,1101466,523906,577560,15,...,Commanders Field,Washington Redskins,62000,0.980299,False,False,False,False,True,False
10844,Washington,redskins,New York,giants,home,2019,1101466,523906,577560,16,...,Commanders Field,Washington Redskins,62000,0.938214,False,False,False,False,True,False
10845,Washington,redskins,Dallas,cowboys,away,2019,1101466,523906,577560,17,...,Commanders Field,Washington Redskins,62000,0.683979,False,False,False,False,True,False

In [64]:
df_games

,year,week,home_team,away_team,winner,tie,day,date,time,pts_win,pts_loss,yds_win,turnovers_win,yds_loss,turnovers_loss,home_team_name,home_team_city,away_team_name,away_team_city
0,2000,1,Minnesota Vikings,Chicago Bears,Minnesota Vikings,NaN,Sun,September 3,1:00PM,30,27,374,1,425,1,Vikings,Minnesota,Bears,Chicago
1,2000,1,Kansas City Chiefs,Indianapolis Colts,Indianapolis Colts,NaN,Sun,September 3,1:00PM,27,14,386,2,280,1,Chiefs,Kansas City,Colts,Indianapolis
2,2000,1,Washington Redskins,Carolina Panthers,Washington Redskins,NaN,Sun,September 3,1:01PM,20,17,396,0,236,1,Redskins,Washington,Panthers,Carolina
3,2000,1,Atlanta Falcons,San Francisco 49ers,Atlanta Falcons,NaN,Sun,September 3,1:02PM,36,28,359,1,339,1,Falcons,Atlanta,49ers,San Francisco
4,2000,1,Pittsburgh Steelers,Baltimore Ravens,Baltimore Ravens,NaN,Sun,September 3,1:02PM,16,0,336,0,223,1,Steelers,Pittsburgh,Ravens,Baltimore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5319,2019,Division,Kansas City Chiefs,Houston Texans,Kansas City Chiefs,NaN,Sun,January 12,3:05PM,51,31,434,1,442,1,Chiefs,Kansas City,Texans,Houston
5320,2019,Division,Green Bay Packers,Seattle Seahawks,Green Bay Packers,NaN,Sun,January 12,6:40PM,28,23,344,0,375,0,Packers,Green Bay,Seahawks,Seattle
5321,2019,ConfChamp,Kansas City Chiefs,Tennessee Titans,Kansas City Chiefs,NaN,Sun,January 19,3:05PM,35,24,404,0,295,0,Chiefs,Kansas City,Titans,Tennessee
5322,2019,ConfChamp,San Francisco 49ers,Green Bay Packers,San Francisco 49ers,NaN,Sun,January 19,6:40PM,37,20,354,0,358,3,49ers,San Francisco,Packers,Green Bay
5323,2019,SuperBowl,Kansas City Chiefs,San Francisco 49ers,Kansas City Chiefs,NaN,Sun,February 2,6:30PM,31,20,397,2,351,2,Chiefs,Kansas City,49ers,San Francisco